language: php

php:
    - 5.5
    - 5.6
  
before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    
script:
    - composer install --prefer-source
    - vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
    - vendor/bin/php-cs-fixer fix -v --fixers=-empty_return --diff --dry-run ./src
    - vendor/bin/php-cs-fixer fix -v --fixers=-empty_return --diff --dry-run ./test

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
